# [module.hugoVersion]
# min = "0.111.3"

[[module.imports]]
path = "github.com/hbstack/hb"

[[module.imports]]
path = "github.com/hugomods/icons/vendors/bootstrap"

# [params.hb.iframe]

# [params.hugopress.modules.hb-iframe.hooks.body-end]
# cacheable = true
